name: Deploy Production
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Build assets
        run: yarn build

      - name: Deploy hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_SUSHI37 }}'
          channelId: live
          projectId: prod-admin-ui-gharkokaam